name: comparaprecios
description: Comparativa de precios entre proveedores para cocina profesional.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  fl_chart: ^0.69.0
  intl: ^0.19.0
  pdf: ^3.11.1
  printing: ^5.13.2
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  http: ^1.2.2
  share_plus: ^10.1.2
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#1B5E20"
  image: assets/icono.png
  android_12:
    color: "#1B5E20"
    image: assets/icono.png
  android: true
  ios: false
  web: false

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icono.png"
  adaptive_icon_background: "#1B5E20"
  adaptive_icon_foreground: "assets/icono.png"

flutter:
  uses-material-design: true
