// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4qVhFLfQoqWyJuXtOl7f_5Hjypcp3JfY',
    appId: '1:1079747123375:web:519908be9d18e0651c9c5a',
    messagingSenderId: '1079747123375',
    projectId: 'comparaprecio-a1191',
    authDomain: 'comparaprecio-a1191.firebaseapp.com',
    storageBucket: 'comparaprecio-a1191.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBScxuF6RexHPPNIjwChQAO5vGLzmDRI-M',
    appId: '1:1079747123375:android:5b90d47cacb4a24e1c9c5a',
    messagingSenderId: '1079747123375',
    projectId: 'comparaprecio-a1191',
    storageBucket: 'comparaprecio-a1191.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX1GIGpL0AJ2XnmEsrNu1l4aFgQVh7r4M',
    appId: '1:1079747123375:ios:958874b106cf0fb41c9c5a',
    messagingSenderId: '1079747123375',
    projectId: 'comparaprecio-a1191',
    storageBucket: 'comparaprecio-a1191.firebasestorage.app',
    iosBundleId: 'com.joseluengo.comparaprecios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX1GIGpL0AJ2XnmEsrNu1l4aFgQVh7r4M',
    appId: '1:1079747123375:ios:958874b106cf0fb41c9c5a',
    messagingSenderId: '1079747123375',
    projectId: 'comparaprecio-a1191',
    storageBucket: 'comparaprecio-a1191.firebasestorage.app',
    iosBundleId: 'com.joseluengo.comparaprecios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4qVhFLfQoqWyJuXtOl7f_5Hjypcp3JfY',
    appId: '1:1079747123375:web:636c34b03d51c3bb1c9c5a',
    messagingSenderId: '1079747123375',
    projectId: 'comparaprecio-a1191',
    authDomain: 'comparaprecio-a1191.firebaseapp.com',
    storageBucket: 'comparaprecio-a1191.firebasestorage.app',
  );
}
