name: Deploy web (Firebase Hosting)

on:
  workflow_dispatch: {}        # botón manual en la pestaña Actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.2'
          channel: stable
          cache: true

      - name: Dependencias
        run: flutter pub get

      - name: Build web (release)
        run: flutter build web --release

      - name: Desplegar a Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: comparaprecio-a1191
